### ISSUE TITLE
Test output gets swallowed when --jobs > 1

### ISSUE THREAD

**Issue by oalders** [houseabsolute/test-class-moose#108] opened 2020-09-21 02:30 UTC
Not sure if the issue is with `Test::Class::Moose`, but I thought this would be a good starting point. I took @oschwald's demonstration of the issue and created a git repo to make it easier to replicate.

```sh
git clone https://github.com/oalders/test-jobs-behaviour
cd test-jobs-behaviour
prove -v --jobs 1 t/runner.t
prove -v --jobs 2 t/runner.t
```

Output should be similar to:

```sh
$ prove -v --jobs 1 t/runner.t
t/runner.t ..
1..1
not ok 1 - TestsFor::DateTime {
    1..1
    not ok 1 - test_constructor {
        not ok 1
        ok 2 - DateTime->can('new')
        ok 3 - An object of class 'DateTime' isa 'DateTime'
        ok 4 - ... and the year should be correct
        1..4
    }
}
        #   Failed test at t/lib/TestFor/DateTime.pm line 10.
    # Failed test 'test_constructor'
    # at /Users/olafalders/.plenv/versions/5.30.3/lib/perl5/site_perl/5.30.3/Test2/Tools/AsyncSubtest.pm line 23.

# Failed test 'TestsFor::DateTime'
# at /Users/olafalders/.plenv/versions/5.30.3/lib/perl5/site_perl/5.30.3/Test2/Tools/AsyncSubtest.pm line 23.
# IPC is waiting for children to finish...
# Looks like you failed 1 test of 1.
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests

Test Summary Report
-------------------
t/runner.t (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=1, Tests=1,  1 wallclock secs ( 0.02 usr  0.01 sys +  0.74 cusr  0.10 csys =  0.87 CPU)
Result: FAIL

$ prove -v --jobs 2 t/runner.t

not ok 1 - TestsFor::DateTime {
        #   Failed test at t/lib/TestFor/DateTime.pm line 10.
    # Failed test 'test_constructor'
    # at /Users/olafalders/.plenv/versions/5.30.3/lib/perl5/site_perl/5.30.3/Test2/Tools/AsyncSubtest.pm line 23.

# Failed test 'TestsFor::DateTime'
# at /Users/olafalders/.plenv/versions/5.30.3/lib/perl5/site_perl/5.30.3/Test2/Tools/AsyncSubtest.pm line 23.
# Looks like you failed 1 test of 1.
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests

Test Summary Report
-------------------
t/runner.t (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=1, Tests=1,  1 wallclock secs ( 0.02 usr  0.01 sys +  0.51 cusr  0.05 csys =  0.59 CPU)
Result: FAIL
```

It looks like having more than 1 test jobs creates the problem.

**Comment by autarch** [comment] 2020-09-21 02:33
I think your `prove` needs `-v` to demonstrate this, but yes, I think this is a real bug. And I'm not sure if it's in TCM or in the Test2 stack somewhere.

**Comment by oalders** [comment] 2020-09-21 02:35
Ah, right. I've got:

```
$ cat ~/.proverc
--color
--lib
--verbose
```

I'll update the initial comment.

**Comment by oalders** [comment] 2020-09-21 02:54
```sh
$ yath t/runner.t

** Defaulting to the 'test' command **

[  FAIL  ]  job  1  +~TestsFor::DateTime
< REASON >  job  1    Subtest failures were encountered (Count: 1)
[  FAIL  ]  job  1    +~test_constructor
[  FAIL  ]  job  1    | + <UNNAMED ASSERTION>
(  DIAG  )  job  1    | | ----- START -----
  Failed test at t/lib/TestFor/DateTime.pm line 10.
(  DIAG  )  job  1    | | ------ END ------
            job  1    | ^
(  DIAG  )  job  1    | ----- START -----
Failed test 'test_constructor'
at /Users/olafalders/.plenv/versions/5.30.3/lib/perl5/site_perl/5.30.3/Test2/Tools/AsyncSubtest.pm line 23.
(  DIAG  )  job  1    | ------ END ------
            job  1    ^
(  DIAG  )  job  1    ----- START -----
Failed test 'TestsFor::DateTime'
at /Users/olafalders/.plenv/versions/5.30.3/lib/perl5/site_perl/5.30.3/Test2/Tools/AsyncSubtest.pm line 23.
(  DIAG  )  job  1    ------ END ------
(  DIAG  )  job  1    Looks like you failed 1 test of 1.
( FAILED )  job  1    t/runner.t
< REASON >  job  1    Test script returned error (Err: 1)
< REASON >  job  1    Errors were encountered (Count: 1)
< REASON >  job  1    ----- START -----
Assertion failures were encountered (Count: 1)
< REASON >  job  1    ------ END ------
< REASON >  job  1    Subtest failures were encountered (Count: 1)

The following jobs failed:
+--------------------------------------+------------+
| Job ID                               | Test File  |
+--------------------------------------+------------+
| 98EB651E-FBB5-11EA-BBDB-AC0B1D8DDE98 | t/runner.t |
+--------------------------------------+------------+

                                Yath Result Summary
-----------------------------------------------------------------------------------
     Fail Count: 1
     File Count: 1
Assertion Count: 6
      Wall Time: 1.98 seconds
       CPU Time: 1.43 seconds (usr: 0.22s | sys: 0.05s | cusr: 0.96s | csys: 0.20s)
      CPU Usage: 72%
    -->  Result: FAILED  <--
```

**Comment by oalders** [comment] 2020-09-21 02:55
With `-m` passed to `prove`:

```sh
$ prove --jobs 2 -lm t/runner.t

not ok 1 - TestsFor::DateTime {
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests

Test Summary Report
-------------------
t/runner.t (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=1, Tests=1,  0 wallclock secs ( 0.02 usr  0.00 sys +  0.59 cusr  0.07 csys =  0.68 CPU)
Result: FAIL
```

**Comment by oalders** [comment] 2020-09-21 02:57
```sh
$ yath -j2 t/runner.t

** Defaulting to the 'test' command **

[  FAIL  ]  job  1  +~TestsFor::DateTime
< REASON >  job  1    Subtest failures were encountered (Count: 1)
[  FAIL  ]  job  1    +~test_constructor
[  FAIL  ]  job  1    | + <UNNAMED ASSERTION>
(  DIAG  )  job  1    | | ----- START -----
  Failed test at t/lib/TestFor/DateTime.pm line 10.
(  DIAG  )  job  1    | | ------ END ------
            job  1    | ^
(  DIAG  )  job  1    | ----- START -----
Failed test 'test_constructor'
at /Users/olafalders/.plenv/versions/5.30.3/lib/perl5/site_perl/5.30.3/Test2/Tools/AsyncSubtest.pm line 23.
(  DIAG  )  job  1    | ------ END ------
            job  1    ^
(  DIAG  )  job  1    ----- START -----
Failed test 'TestsFor::DateTime'
at /Users/olafalders/.plenv/versions/5.30.3/lib/perl5/site_perl/5.30.3/Test2/Tools/AsyncSubtest.pm line 23.
(  DIAG  )  job  1    ------ END ------
(  DIAG  )  job  1    Looks like you failed 1 test of 1.
( FAILED )  job  1    t/runner.t
< REASON >  job  1    Test script returned error (Err: 1)
< REASON >  job  1    Errors were encountered (Count: 1)
< REASON >  job  1    ----- START -----
Assertion failures were encountered (Count: 1)
< REASON >  job  1    ------ END ------
< REASON >  job  1    Subtest failures were encountered (Count: 1)

The following jobs failed:
+--------------------------------------+------------+
| Job ID                               | Test File  |
+--------------------------------------+------------+
| 131FE378-FBB6-11EA-A0EA-CC341D8DDE98 | t/runner.t |
+--------------------------------------+------------+

                                Yath Result Summary
-----------------------------------------------------------------------------------
     Fail Count: 1
     File Count: 1
Assertion Count: 6
      Wall Time: 1.18 seconds
       CPU Time: 1.38 seconds (usr: 0.20s | sys: 0.04s | cusr: 0.95s | csys: 0.19s)
      CPU Usage: 116%
    -->  Result: FAILED  <--
```

**Comment by oalders** [comment] 2020-09-21 02:57
Excuse all of the updates. Am working with @exodist to see if this is a Test2 issue.

**Comment by exodist** [comment] 2020-09-21 02:59
This looks like a prove (Test::Harness) issue to me. prove -v seems to be eating STDOUT, the -m merges STDERR to STDOUT (effectively) and -m makes all output go away.

**Comment by exodist** [comment] 2020-09-21 03:09
A simple fail.t with an ok(0) with prove -j2 does not reproduce the problem. However it is pretty obvious the test is outputting everything it should based both on yath, and the prove without -j. I am still 90% sure prove is doing something under -j that eats STDOUT. But I am not sur eif maybe it is buffering on something that is a bad assumption, or a safe assumption that Test2 mistakenly never outputs?

**Comment by autarch** [comment] 2020-10-18 20:40
I'm going to close this since it seems to be an issue elsewhere.

**Closed by autarch** 2020-10-18 20:40 UTC
